### ISSUE TITLE
[Parse error on extra json file.] [ws-sbom-generator] JSON parse error.

### ISSUE THREAD

**Issue by Justin-Powers** [whitesource-ps/ws-sbom-generator#127]
Hello,

I am getting a parse error error for the extra json file.  Looking at the json file.  I can't see anything that looks formatting incorrectly. 

ERROR 2022-07-25 13:11:25,853 4405175808 sbom_generator: Unable to parse file: /Users/jpowers/Desktop/whitesource_sbom/VW6.2_linux/sbom_extra.json

/Users/jpowers/Desktop/whitesource_sbom/VW6.2_linux
jpowers-mbp:VW6.2_linux jpowers$ ls
sbom_extra.json

jpowers-mbp:VW6.2_linux jpowers$ cat sbom_extra.json 
{
  "namespace": "https://esd.actian.com/product/Vector/6.2/Linux_X86_64-bit/Software_Bill_of_Materials",
  “org_name”: “Actian Corp.”,
  "org_email": "sbom@actian.com",
  "person": "person name",
  "person_email": "person@email.address"
}

I am wondering if it is due to person name and person email left generic.   I was under the impression, since the ws_sbom_generator is creating the report, I do not have to provide an email or name. 

Thanks in advance, Justin

**Comment by DimarrWS** [comment]
Hi @Justin-Powers ! As I see you used “ symbol in the second line (org_name), but need to use " instead it. 
This is an error.

Best Regards,
Dima

**Comment by Justin-Powers** [comment]
Thanks,  I ma not sure how those quotes changed.   That solved it.  
-Justin

**Comment by Justin-Powers** [comment]
closing ticket.
