### ISSUE TITLE
[BUG] [ws-sbom-generator] DEPENDS_ON missing from json output

### ISSUE THREAD

**Issue by kmaloney** [whitesource-ps/ws-sbom-generator#129]
The DEPENDS_ON entries in the json output are missing when using docker image v0.6.8.

**Steps to Reproduce**  
1. Performed Mend scan of https://github.com/f5devcentral/f5-automation-config-converter (main).
2. Create sbom with "ws_sbom_generator -u user-key -k api-key -s project-token -a api-url -t json" using docker image for versions v0.6.6, v0.6.7, and v0.6.8
3. Review output.

**Expected Behavior**  
DEPENDS_ON entries are present in output from v0.6.6 and v0.6.7.

**Environment Details**  
 - ws-sbom-generator docker image
 - v0.6.6, v0.6.7, v0.6.8

**Comment by DimarrWS** [comment]
Hello @kmaloney ! Can you, please, provide me with the name of the project that you use? 
Thanks in advance!

**Comment by kmaloney** [comment]
The viewer was hiding some of the info (treating them as tags).  So, I updated that.

The project name that we use for the scan is the same as the repo "f5-automation-config-converter"

**Comment by kmaloney** [comment]
I generated SBOMs using 0.6.6, 0.6.7, and 0.6.8 (version is an environment variable in our pipeline ).

Thanks for your help,

-Kevin

From: DimarrWS ***@***.***>
Date: Monday, August 22, 2022 at 6:24 AM
To: whitesource-ps/ws-sbom-generator ***@***.***>
Cc: Kevin Maloney ***@***.***>, Mention ***@***.***>
Subject: Re: [whitesource-ps/ws-sbom-generator] [BUG] [ws-sbom-generator] DEPENDS_ON missing from json output (Issue #129)

EXTERNAL MAIL: ***@***.***

Hi @kmaloney<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkmaloney&data=05%7C01%7Ck.maloney%40f5.com%7C747a73eaa68749611b5008da8441a245%7Cdd3dfd2f6a3b40d19be0bf8327d81c50%7C0%7C0%7C637967714714202978%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=P40khxT5j29D%2FQkGOCYxvZm9CMyEu6AcSTxaVh6Jsk8%3D&reserved=0> ! I switched to the private discussion (by e-mail) for more detailed debugging.
Please, see my email from yesterday.

**Comment by DimarrWS** [comment]
Hi @kmaloney !  I understood that you tried to run for all versions of  sbom-generator in your pipeline.
Sorry, I don't understand - is the issue repeated again? 
If yes, please, send me the wrong output by email.
Because of as I wrote in the email I can't reproduce this bug.
Thanks in advance!

**Comment by kmaloney** [comment]
I tried to respond to the email.  I don't see any other options.

**Comment by NatalyaDalid** [comment]
Hi @kmaloney,
There was another internal email from Dima with more details about your case.
It probably hadn't reached you.
Could you please send us a test email to ps@whitesourcesoftware.com, so we will be able to switch to a private conversation?  

Thanks,

**Comment by NatalyaDalid** [comment]
Hi @kmaloney ,
We were able to reproduce this issue and fix it.
Please pull and try the newest version and let us know if the issue has been solved.

Thank you,
PS Mend Team

**Comment by kmaloney** [comment]
Ran a pipeline with 22.8.4.  The problem is fixed.  Thanks.
