### ISSUE TITLE
[Question] [ws-sbom-generator] Cannot run in windows 

### ISSUE THREAD

**Issue by Tom-HY-Tsai** [whitesource-ps/ws-sbom-generator#138]
Hi, 
I tried to run ws-sbom-generator on Windows powershell with command which is successfully executed in linux, but i only got two line:
 _INFO 2022-10-21 18:17:39,630 25936 sbom_generator: Creating SBOM Document from Mend 'ACC_Python'
ERROR 2022-10-21 18:17:41,878 10612 sbom_generator: Error running SBOM Generator_
Is there any suggestion what is going wrong?

**Environment Details**  
 - OS: windows 10 enterprise
 - Browser :chrome, edge
 - Version: v22
![screenshot](https://user-images.githubusercontent.com/60132573/197176566-cb6fcd5a-77d1-4b77-9ee4-530c62463fbc.png)

**Comment by DimarrWS** [comment]
HI @Tom-HY-Tsai !  Unfortunately, I can't reproduce your error still. Can you send me (in private) your JSON file which you are using in --extra parameter? What version of Sbom-generator did you use?

**Comment by Tom-HY-Tsai** [comment]
Hi, DimarrWS

Greeting and Very thanks for your reply!
I just follow command to install sbom-generator, and I found no parameter
to print version i installed (ex: -v), so the hash value of sbom-generator
is provided here for your reference :e968fcbbfa9c0741a0d54c4cd7525149 if
that OK to you .
and I also attach JSON file, I thought, might be wrong, it need a "empty"
JSON as a skeleton for generator, so I copy content from readme and the
file is attached.

please let me know if there is any information you need

Best regards
Tom

DimarrWS ***@***.***> 於 2022年10月23日 週日 下午3:54寫道：

**Comment by DimarrWS** [comment]
Hi @Tom-HY-Tsai ! Can you try to run the tool without -e parameter? Also I hope you have folder Output , which you provide as -o parameter?

**Comment by Tom-HY-Tsai** [comment]
Hi, DimarrWS

Thanks for your reply,
I just ran the tool without -e, and it still fails, and yes, I have output
directory
please check screenshot as attached
Thanks for your help

Best Regards
Tom

DimarrWS ***@***.***> 於 2022年10月24日 週一 下午2:30寫道：

**Comment by DimarrWS** [comment]
Hmmm, I do not see any screenshots here. Looks like nothing attached...
Tom, what is the exact name of your organization on saas environment?

**Comment by Tom-HY-Tsai** [comment]
Hi, DimarrWS

That's kinda weird, I attached it again(screenshot-2.png), and my
organization is ASUS
Thanks

Best Regards
Tom

DimarrWS ***@***.***> 於 2022年10月24日 週一 下午3:16寫道：

**Comment by Tom-HY-Tsai** [comment]
Hi, DimarrWS

I copy my screen as text, please check if you still not receive the
screenshot, i'm sorry that  i need to remove some parameters














*PS C:\Users\TomHY_Tsai> ws_sbom_generator.exe -u <xxxx> -k <xxxxx> -y
organization -a saas -s <xxxx> -o ./output  -t jsonWARNING 2022-10-24
15:01:20,860 20860 sbom_generator:
C:\Users\TomHY_Tsai\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\ws_sbom_generator\resources\sbom_extra.json
configuration file was not found. Be sure to create a file in the following
structure (-e/--extra):            {                "namespace":
"http://CreatorWebsite/pathToSpdx/DocumentName-UUID
<http://CreatorWebsite/pathToSpdx/DocumentName-UUID>",
"org_name": "Organization Name",                "org_email":
***@***.***",                "person": "person name",
"person_email": ***@***.***"            }INFO 2022-10-24
15:01:21,892 5220 sbom_generator: Creating SBOM Document from Mend
'ACC_Python'ERROR 2022-10-24 15:01:23,478 20860 sbom_generator: Error
running SBOM GeneratorPS C:\Users\TomHY_Tsai> dir .\output\PS
C:\Users\TomHY_Tsai>*


Thanks
Best regards,
Tom


Her-Yann Tsai ***@***.***> 於 2022年10月24日 週一 下午3:21寫道：

**Comment by DimarrWS** [comment]
If I understand correct you ran tool successfully on Linux env., right?
Has your Windows computer same access to your environment ? (I mean that IP is in White List)

**Comment by Tom-HY-Tsai** [comment]
Hi, DimarrWS
We found the workaround to fix this issue, it seem the problem is related
to locale,
the tools work when i change system administrative language to us-en
FYI,
Thanks for your help

Best regards,
Tom

DimarrWS ***@***.***> 於 2022年10月24日 週一 下午5:03寫道：

**Comment by DimarrWS** [comment]
I see, Tom. Thank you for the update.
Please, contact me anytime you will have problems with the tool. I will be glad to assist.

BR,
Dima
