### ISSUE TITLE
[BUG] [ws-sbom-generator] Error running SBOM Generator

### ISSUE THREAD

**Issue by RinaGSS** [whitesource-ps/ws-sbom-generator#144]
**Bug Description**  
Use this tool to create SBOM. But always error.
Attached is a screenshot, plz help.
![螢幕擷取畫面 2022-11-24 160012_new](https://user-images.githubusercontent.com/116698911/203884694-d569ae02-3921-45be-a2f8-67d06cf5f8b6.png)

**Comment by DimarrWS** [comment]
Hi @RinaGSS ! As I see on your screenshot you provide -a parameter as https://saas.whitesourcesoftware.com
But need to provide (as described in READ.ME) saas or app or app-eu or saas-eu. 
Please, rerun the tool with -a saas option. 
BR,
Dima

**Comment by RinaGSS** [comment]
I try to use saas or app or app-eu or saas-eu. Neither work.

The error message is as follows:
Generic error on token: 'xxxxxxxxxxxxx'. Error: {"errorCode":1003,"errorMessage":"Invalid product token"}
sbom_generator: Error running SBOM Generator

Why errorMessage is about product token? I input the project token.
But input product token is same error message
sbom_generator: Error running SBOM Generator

**Comment by DimarrWS** [comment]
Hi @RinaGSS ! You should provide saas or app or app-eu or saas-eu depending on WHERE your Mend system is hosted.
Are you use https://saas.whitesourcesoftware.com or https://app.whitesourcesoftware.com , for example, or another URL?
Please, provide me with your command line so I can reproduce your error (without tokens, of course).  Also, please, send me the name of your company and your project(product) name. Thanks in advance!

**Comment by RinaGSS** [comment]
The first dialog use https://saas.whitesourcesoftware.com/.
Could you provide me your e-mail? I'll give you the full command line including the token.
Thanks.

**Comment by DimarrWS** [comment]
Yes, sure. My email is dmitry.rumyancev@whitesourcesoftware.com

**Comment by RinaGSS** [comment]
Resolved
