### ISSUE TITLE
[BUG] [ws-sbom-generator] Generation of "licenseInfoFromFiles" field is not idempotent

### ISSUE THREAD

**Issue by olhado** [whitesource-ps/ws-sbom-generator#148]
**Bug Description**  
If a dependency has been identified to have more than one license in the `licenseInfoFromFiles` field, the `licenseDeclared` field will change between runs, even when nothing has changed. 

**Steps to Reproduce**  
1. Run the `ws_sbom_generator` against a project with a dependency with multiple detected licenses
2. Save the output
3. Run the `ws_sbom_generator` against the same project with a dependency with multiple detected licenses (without updating the project in between).
4. Save the output
5. Compare the two output files. Some of the same dependencies will have different ordering in `licenseInfoFromFiles` and the `licenseDeclared` field will differ.

**Expected Behavior**  
The list of licenses in `licenseInfoFromFiles` should have consistent ordering, and `licenseDeclared` should have the same result between runs, if licenses haven't changed.

**Environment Details**  
 - Version 0.6.8

**Comment by DimarrWS** [comment]
Hi @olhado ! Can you please provide me Organization name, URL of your hosting (saas, app or so on), and project name? 
It will be really useful for reproducing the issue.
Thanks in advance,
Dima

**Comment by olhado** [comment]
Could I send it to a support email instead?

**Comment by DimarrWS** [comment]
Please, send me directly by email at dmitry.rumyancev@whitesourcesoftware.com
