### ISSUE TITLE
[BUG] [ws-sbom-generator] CLI argument breaking changes

### ISSUE THREAD

**Issue by RalfEckstein** [whitesource-ps/ws-sbom-generator#160]
Hi,

with the 23.1 version, the command line option `--license_text` was changed to `--licensetext` (underscore removed). As we're using this tool in our build pipelines (as suggested by our customer success manager at Mend) this change caused our build pipelines to fail.

This was easy to fix so we're fine now. 

What I would like to as for: please do not introduce breaking changes in future versions of your PS tools. That would be really helpful.

Thank you very much,

Ralf

**Comment by tidharm** [comment]
Hi @RalfEckstein,

Thank you so much for your feedback.
This is indeed an unfortunate mistake on our end.

We actually have a process in place to avoid such issues, and by policy, even when we change config/cli parameters, we make sure to still allow the old ones to be used, even if not documented anymore. Evidently, we missed this time.

We've fixed this now, by allowing usage of both the previous `license_text` and the new `licensetext` (see commit [96ba1db](https://github.com/whitesource-ps/ws-sbom-generator/pull/162/commits/96ba1dbda09cf932cbd5e56ba81b72f1b4f42e13)). A new release will be published shortly.

We've also updated the [documentation](https://github.com/whitesource-ps/ws-sbom-generator/blob/master/README.md), so I'm hoping you'd find it clearer and easy to use.

Please let us know if you encounter any further issues.
Once again, we appreciate your feedback.

**Comment by tidharm** [comment]
Hi @RalfEckstein,

Release [v23.1.1.3](https://github.com/whitesource-ps/ws-sbom-generator/releases/tag/v23.1.1.3) is now available. Please let me know whether it addresses the issue or not.

**Comment by RalfEckstein** [comment]
Hi @tidharm,

thanks for the explanation - and good to hear about the processes in place.

As we've already changed our build-pipelines to use the new parameter name, it's not an issue for us any more. But thanks anyway for re-establishing backward compatibility.

Thanks, Ralf
