### ISSUE TITLE
 ws-sbom-generator - customer reported issue

### ISSUE THREAD

**Issue by ioana-nicolae** [whitesource-ps/ws-sbom-generator#38]
**Bug Description**  
ICICI from Meteonic has tried setting up the ws-sbom-generator and they are facing the issue presented in the attached screenshot

**Screenshots**  
<img width="960" alt="SPDX" src="https://user-images.githubusercontent.com/72495703/142591876-752df521-103e-41a3-9571-4c7f5c062415.png">

the customer asked for WS to create this issue on their behalf. any additional details needed from their side please let us know

**Comment by tamari-oz** [comment]
Hi @ioana-nicolae,

The upstream spdx-suite version we are using (0.7) was not released yet. 
In order to use our tool now, it is required to manually download and install our [spdx-tools package](https://github.com/spdx/tools) as instructed in the README.
I hope this will change soon.
