### ISSUE TITLE
[BUG] [ws-sbom-generator] Incomplete Library Relationships

### ISSUE THREAD

**Issue by benavidezb** [whitesource-ps/ws-sbom-generator#50]
The output (tv, yml, json, xml, and rdf) only appears to define relationships between top level packages and their immediate dependencies but does not include higher order dependencies i.e. dependencies of dependencies. For example, I have a project with the following dependency hierarchy:
runtime.win.system.net.primitives.4.3.0.nupkg
 |
 -> system.resources.resourcemanager.4.3.0.nupkg
	 |
	 --> system.globalization.4.3.0.nupkg

And yet only the following relationship exists that has any of these package names:
Relationship: SPDXRef-PACKAGE-runtime.win.system.net.primitives.4.3.0.nupkg DEPENDS_ON SPDXRef-PACKAGE-system.resources.resourcemanager.4.3.0.nupkg

Is it possible to generate a report that includes all dependencies? Specifically, I would like to be able to recreate the library hierarchy that can be seen in the WhiteSource UI.

**Comment by tamari-oz** [comment]
Which version of the tool are you using? 
Nested package relationships was added in 0.3.4 and only after 0.3.5 you'll see relationships in non TV output.

The data in the tool is based on WhiteSource lib modeling so it is mandatory that the WhiteSource App will be able to recognize this nested relationship.

**Comment by benavidezb** [comment]
I was running 0.3.3. I tested this on 0.3.6 and 0.3.7a1 and it looks good! Thank you.
