### ISSUE TITLE
[BUG] [ws-sbom-generator] Invalid PackageChecksum Algorithm Descriptor

### ISSUE THREAD

**Issue by benavidezb** [whitesource-ps/ws-sbom-generator#51]
The algorithm listed in the PackageChecksum field states "SHA-1"; however, according to SPDX Specification v2.2 Section 3.10.4, the only valid algorithms for this field are SHA1, SHA224, SHA256, SHA384, SHA512, MD2, MD4, MD5, or MD6.

The use of "SHA-1" instead of "SHA1" causes the SBOM generator output to fail the Verify command from https://github.com/spdx/tools (can also use https://tools.spdx.org/app/validate/).

**Comment by tamari-oz** [comment]
Thanks! I fixed the algorithm identifier in the tool's next version (>0.3.6).

**Comment by benavidezb** [comment]
Thank you for the quick fix! I checked this in 0.3.7a1 and it works perfectly.
