### ISSUE TITLE
[FR] [ws-sbom-generator] Change RDF Report File Extension or Naming Convention

### ISSUE THREAD

**Issue by benavidezb** [whitesource-ps/ws-sbom-generator#53]
Using the _all_ argument with the _--type_ option only outputs xml, yml, json, and tv but does not include rdf. This is probably because the _rdf_ option outputs reports with a .xml file extension. Would it be possible to instead have this output with a .rdf extension and include all reports (xml, yml, json, tv, and rdf) when running _--type all_? Or if the extension must be maintained, could it instead be output as "filename.rdf.xml"?

**Comment by tamari-oz** [comment]
In version 0.3.6 the suffix for RDF format is 'rdf'.

**Comment by benavidezb** [comment]
I was running <0.3.6 but after updating I see this now. Thank you!
