### ISSUE TITLE
[BUG] [ws-sbom-generator] /bin/sh: 1: sbom_generator: not found when running using Docker container

### ISSUE THREAD

**Issue by hvincentwss** [whitesource-ps/ws-sbom-generator#55]
**Bug Description**  
When running the sbom generator using docker I get the following error: 
/bin/sh: 1: sbom_generator: not found

**Steps to Reproduce**  
1. Pull latest Docker image
2. Run: docker run --name ws-sbom-generator -v C:\Users\HannaVincent\Desktop\Cases\SBOM\test1:/opt/ws-sbom-generator/sbom-generator/output -e WS_USER_KEY=<redacted> -e WS_TOKEN=<redacted> -e WS_SCOPE=<redacted>   whitesourcetools/ws-sbom-generator

**Expected Behavior**  
SBOM generator runs

**Environment Details**  
 - OS: Windows

**Comment by tamari-oz** [comment]
Hi,
I fixed a bug in the Dockerfile. It should be fine in the next version (>0.3.7).

**Comment by NatalyaDalid** [comment]
Hi @hvincentwss,
Please let us know if the issue is solved and can be closed.

Thanks,
WhiteSource PS Team
