### ISSUE TITLE
[Question] [ws-tool-name] Question Topic

### ISSUE THREAD

**Issue by RobMarion** [whitesource-ps/ws-sbom-generator#56]
**Question**  
I am looking for additional documentation on this feature:

     -e EXTRA, --extra EXTRA
                           Extra configuration of SBOM

Can you give examples of how it is used?

**Comment by tamari-oz** [comment]
Hi,

The extra configuration file allows to add details to the report that are not available in WS App.
The structure of the file can be found [here](https://github.com/whitesource-ps/ws-sbom-generator/blob/master/ws_sbom_generator/resources/sbom_extra.json).

I added the json to the README for more convenience.

**Comment by NatalyaDalid** [comment]
Hi @RobMarion,
Please let us know if the issue is solved and can be closed.

Thanks,
WhiteSource PS Team
