### ISSUE TITLE
[BUG] [ws-sbom-generator] Extracted Licenses Section Does Not Include All Licenses

### ISSUE THREAD

**Issue by benavidezb** [whitesource-ps/ws-sbom-generator#60]
In version 0.3.8a2, it appears only Microsoft-.NET-Library licenses are included in the Extracted Licenses section. Should this include all licenses?

**Comment by tamari-oz** [comment]
The way I interpreted the spec is that Extracted license is for licenses which are not in the SPDX list.

Do you see any other non-SPDX license that is not in the **ExtractedLicensingInfo**?

**Comment by benavidezb** [comment]
I didn't see that in the spec, but I'll take your word for it. Thanks for the info!
