### ISSUE TITLE
[Question] [ws-sbom-generator] SBOM SPDX question

### ISSUE THREAD

**Issue by milica144** [whitesource-ps/ws-sbom-generator#82]
I call Sbom generator with: ws_sbom_generator -u xxx -k uuu -s uuu f -y product -a https://app-eu.whitesourcesoftware.com/ -t json

Sbom_generator creating SBOM reports on all Organization Projects and
I get this message:
ERROR 2022-02-18 20:07:01,370 17480 sbom_generator: Unable to parse file: C:\Users\ristic.milica\AppData\Roaming\Python\Python39\site-packages\ws_sbom_generator\resources\sbom_extra.json

How to generate a report only for one product? Can you give me an example for sbom_extra.json?

**Comment by NatalyaDalid** [comment]
Hi @milica14,

Please find the example for the extra.json [here](https://github.com/whitesource-ps/ws-sbom-generator/tree/master/ws_sbom_generator/resources). Your cmd line looks correct and using the specified sbom_extra.json format should solve your issue. Also, please ensure that your WS_TOKEN is a Product Admin Token.

Besides, it is highly recommended, for security reasons, to hide your keys when you publish them in public spaces. I would recommend recreating the user key in your WhiteSource environment.

Please let us know if you were able to make it work.

Thanks,
WhiteSource PS Team

**Comment by milica144** [comment]
Hi Natalya, 

When I run my cmd line, Sbom_generator creates SBOM reports on all Organization Projects. I want to create reports for one specified product. How to do that? I am not sure what to put in sbom_extra.json in filed "namespace"?

**Comment by NatalyaDalid** [comment]
Hi @milica144 ,

For getting SBOM for the specific product, please run with the specific Product Admin Token and set the parameter -y to 'product'. Here's the example:  `ws_sbom_generator -u <YOUR_WS_USER_KEY> -y product -k <YOUR_WS_PRODUCT_TOKEN> -s <YOUR_WS_PROJECT_TOKEN>`

Regarding the <WS_PROJECT_TOKEN> you are absolutely correct, it can be found on the Project Administration page.

Also, you can find more information about the namespace field [here](https://spdx.github.io/spdx-spec/document-creation-information/#65-spdx-document-namespace-field).

Thanks,
Natalya
WhiteSource PS Team

**Comment by milica144** [comment]
Hi Natalya, 

-k is used for ORG token, not for product token. When I try -k <YOUR_WS_PRODUCT_TOKEN> I get:Error: {"errorCode":1002,"errorMessage":"Invalid organization token"}.

**Comment by NatalyaDalid** [comment]
Hi @milica144 ,

-k is used for both cases. In the case of the PRODUCT_TOKEN please add the following parameter: -y product

**Comment by milica144** [comment]
Hi Natalya, 

This is cmd line:
ws_sbom_generator -u USER KEY -y product -k PRODUCT KEY -s PROJECT KEY -a https://app-eu.whitesourcesoftware.com -t json
I get:  Error: {"errorCode":1002,"errorMessage":"Invalid organization token"}

**Comment by NatalyaDalid** [comment]
Hi @milica144 ,

The command line you have shared should work. Let's just double-check the paramterers:

- USER KEY - the Admin User Key (can be found in Profile page ->User Keys section) or Active Service User Key (can be found in Admin page -> Users)
- PRODUCT KEY - Product Token from the specific Product Administration page 
- PROJECT KEY - Project Token from the specific Project Administration page 

If you still face issues, please contact us privately by email, ps@whitesourcesoftware.co, so we would be able to debug your specific case.

Thanks
Natalya

**Comment by NatalyaDalid** [comment]
Hi @milica144 ,

Also please double-check your WhiteSource URL.
The default is saas, but if you work with the app-eu for example, you have to add the following parameter as well: `-a app-eu`

Please let us know if it helped.

Thanks,
WhiteSource PS Team

**Comment by rammatzkvosky** [comment]
Hi @milica144 ,
There was a typo in the mail address we provided.
Please share the running command to ps@whitesourcesoftware.com

**Comment by rammatzkvosky** [comment]
Hi @milica144, we released version 0.5.4 which fix the issue.

Kindly let us know if it helped.

Thanks,
WhiteSource PS Team

**Comment by milica144** [comment]
Hi @rammatzkvosky,
Thank you, I finally generate reports for one product. 
But, I have a question about licenses detected by WS. WS detects GPL2.0, WS SBOM generator generates reports where this license show as  GPL2.0 and  GPL-2.0-with-classpath-exception which are deprecated (https://spdx.org/licenses/). Is it possible to get SPDX from SPDX License list?

**Comment by NatalyaDalid** [comment]
Hi @milica144 ,

We apologize for the delay with an answer. This issue is currently in our Backlog and will be taken up soon. We will keep you updated.

Thanks,
Mend PS Team

**Comment by DimarrWS** [comment]
@milica144 Hello! We deployed a new version of SBOM generator. Please, check it. If you will have more issues - inform me, and I'll test and fix ASAP.
