### ISSUE TITLE
[FR] [ws-sbom-generator] SBOM generator should not require admin rights

### ISSUE THREAD

**Issue by RalfEckstein** [whitesource-ps/ws-sbom-generator#95]
When using `ws_sbom_generator` the documentation states that the user behind the provided user key needs to be product administrator (when using the `-y product` option) or organisation admin.

We're are using service users for our build pipelines to run the scanner and `ws_sbom_generator`. As the tokens for these users are configured in the build pipelines we consider it as a security risk if these tokens provide admin rights - even if this is "only" on the product level.

It would be very helpful if the required rights for the user token passed to `ws_sbom_generator` could be lowered.

**Comment by rammatzkvosky** [comment]
Hi @RalfEckstein ,

I checked with our product team and the recommendation is to use the [Auditor role](https://docs.mend.io/bundle/sca_user_guide/page/managing_organization_assignment_roles.html#Auditor) which has an organization-level read-only permissions.

You can find it at Home > Admin > Assignments Menu

![image](https://user-images.githubusercontent.com/41573396/173776729-9639b525-c5a0-4e77-864b-82216792e6eb.png)

**Comment by rammatzkvosky** [comment]
Hi @RalfEckstein ,

Could you kindly share the command you run in the pipline for the `ws_sbom_generator` ( please mask the tokens ).

Thanks,

Ram

**Comment by RalfEckstein** [comment]
Hi @rammatzkvosky,

this is the complete log output of the Azure DevOps build step calling `ws_sbom_generator`: [ws-sbom-generator.log](https://github.com/whitesource-ps/ws-sbom-generator/files/9000594/ws-sbom-generator.log).

And this is the script `source`'d by the build step - it's calling `ws_sbom_generator`: [create-sbom.zip](https://github.com/whitesource-ps/ws-sbom-generator/files/9000601/create-sbom.zip)

Thanks, Ralf

**Comment by rammatzkvosky** [comment]
Hi @RalfEckstein ,

Sorry for the delay in my reply.
Please try running our [latest version ](https://pypi.org/project/ws-sbom-generator/0.6.6/)( I tested it with the same setup you did and it worked as expected ).

Kindly let me know how it runs for you.

Thanks,
Ram

**Comment by RalfEckstein** [comment]
Hi @rammatzkvosky,

I re-ran the pipeline with the new version but I still get the same error message when removing the service user from the product admin group (double-checked that the service user still is part of the auditors group).

See attached log output. If I read that properly, version 0.6.6 is indeed pulled.

Thanks, Ralf

[ws_sbom_generator_auditors_0.6.6.log](https://github.com/whitesource-ps/ws-sbom-generator/files/9131022/ws_sbom_generator_auditors_0.6.6.log)

**Comment by rammatzkvosky** [comment]
Hi @RalfEckstein ,

We made some changes in [version 0.6.7](https://pypi.org/project/ws-sbom-generator/0.6.7/)--> please try and update us with the results.
Thanks,
Ram

**Comment by rammatzkvosky** [comment]
Hi @RalfEckstein ,

Did you have the chance to try it?
We released a [new version](https://pypi.org/project/ws-sbom-generator/0.6.8/) a few days ago.

Thanks,
Ram

**Comment by rammatzkvosky** [comment]
Hi @RalfEckstein ,
We will close this issue for now.

if you are still facing the same issue we can re-open it.

Thanks,
Ram

**Comment by RalfEckstein** [comment]
Hi @rammatzkvosky,
please excuse my late response. Just today I had a chance to re-test it and ws_sbom_generator now is working w/o the user being a product admin. It's sufficient if the user is an auditor.
Thank you very much for your assistance,
Ralf
