### ISSUE TITLE
[BUG] [ws-sbom-generator] SPDX field extractedText should be filled with full licence text for all components

### ISSUE THREAD

**Issue by RalfEckstein** [whitesource-ps/ws-sbom-generator#96]
**Bug Description**  
In the SPDX output created by ws-sbom-generator we see two issues with the SPDX field `extractedText`:
1. The field is filled with the licence name. According to the SPDX standard it should be filled with the full licence text as provided with the component: "*Purpose: Provide a copy of the actual text of the license reference extracted from the package or file that is associated with the License Identifier Assigned to aid in future analysis.*" - see https://spdx.org/rdf/spdx-terms-v2.0/dataproperties/extractedText___-1947076550.html
2. The `extractedText` field seems only to be present for licences w/o an SPDX ID. For providing an SBOM compliant with many of the open source licences we need to deliver the full licence text for each component. Thus, the full licence text should be present for *all* components listed in the SPDX file. Please not that for licences like MIT or ISC this licence text should not be the template with the placeholders "<YEAR> <COPYRIGHT HOLDER>" but should contain the original licence text as provided with the component or the present in the component's source code.

**Steps to Reproduce**  
1. scan a project with WhiteSource scanner
2. obtain project token for the scan
4. run `ws_sbom_generator -u $WS_USERKEY -k $WS_APIKEY -s $WS_PROJECTTOKEN -a $WS_URL -t json -e ./whitesource/sbom_extra.json -o ./whitesource/artifacts` 
5. inspect SPDX json output
 
**Expected Behavior**  
see **Bug Description**  

**Environment Details**  
reproducible on Azure DevOps build pipelines using the `ubuntu-20.04` image

**Comment by RalfEckstein** [comment]
Hi @DimarrWS,

I just did as you said - but I couldn't observe any change in the output, I'm afraid.

This is the log output of the build step for `ws_sbom_generator`: [pipeline-spdx-new.log](https://github.com/whitesource-ps/ws-sbom-generator/files/8993237/pipeline-spdx-new.log)

When comparing this to an older run ([pipeline-spdx-old.log](https://github.com/whitesource-ps/ws-sbom-generator/files/8993240/pipeline-spdx-old.log)) I can see a change in the `ws_sbom_generator`'s version number: it changed from `ws_sbom_generator-0.5.8-py3-none-any.whl` to `ws_sbom_generator-0.6.1-py3-none-any.whl`. 

However, the resulting SPDX file still has just the licence name in the `extractedText` field and the `hasExtractedLicensingInfos` section only contains 3 licences - whereas the project contains 6 different licences in total. This is the created SPDX file:[WhiteSource LicenseCheck_master_0.1.0-beta.180 SBOM report-SPDX-2.2.zip](https://github.com/whitesource-ps/ws-sbom-generator/files/8993264/WhiteSource.LicenseCheck_master_0.1.0-beta.180.SBOM.report-SPDX-2.2.zip)

Am I using the right version? Can you see what could be wrong?`

Thanks, Ralf

**Comment by DimarrWS** [comment]
Hi @RalfEckstein ! I suppose this is my mistake. I have not described it to you in detail. I apologize. The sbom-generator use ws-sdk package. This package was updated too. You need completely to reinstall sbom-generator. It has to take the last version of ws-sdk package (0.10.3) also.

**Comment by RalfEckstein** [comment]
Hi @DimarrWS,

`ws_sbom_generator` runs on an Azure DevOps build machine provided by Microsoft. This means that we always start with a "clean" machine and install everything from scratch. The log output provided above it seems to indicate that version 0.10.3 of `ws-sdk` already was used in my test:
```
2022-06-27T15:02:46.7789249Z Collecting ws-sdk==0.10.3
2022-06-27T15:02:46.7868417Z   Downloading ws_sdk-0.10.3-py3-none-any.whl (47 kB)
```
Thanks, Ralf

**Comment by DimarrWS** [comment]
Hi @RalfEckstein  First, please, use pip install ws-sbom-generator == 0.6.3. Second, I ran it locally and see that extractedText contains License text in **case** this text was presented by SPDX Org. We put the name instead text now just in case that license text was not found on spdx.org

**Comment by RalfEckstein** [comment]
Hi @DimarrWS, 

thanks for testing and the explanation. Using the licence text from spdx.org is not exactly what we need. Our legal advisors tell us that we must use the licence text as provided in the package or the corresponding source code. In my understanding this matches the citation from the SPDX standard in the bug description where it says "_the actual text of the license reference extracted from the package or file_".

We can see in Mend's UI that the original licence text (as provided in package or source code) _is_ available for many packages. Our requirement would be to use this information.

Thanks, Ralf

**Comment by RalfEckstein** [comment]
Hi @DimarrWS,

when re-testing with an enforced 0.6.3 version (see [ws-sbom-generator-0.6.3.log](https://github.com/whitesource-ps/ws-sbom-generator/files/9010514/ws-sbom-generator-0.6.3.log)) I still get the same SPDX json content:  [WhiteSource LicenseCheck_master_0.1.0-beta.180 SBOM report-SPDX-2.2 (1).zip](https://github.com/whitesource-ps/ws-sbom-generator/files/9010517/WhiteSource.LicenseCheck_master_0.1.0-beta.180.SBOM.report-SPDX-2.2.1.zip)

Thanks, Ralf

**Comment by DimarrWS** [comment]
Hi @RalfEckstein ! Please, take version 0.6.4. I'll wait your feedback

**Comment by Markus-Wild** [comment]
We have the same problem. The SPDX File should refer to the actual License Text, like the REST API getProductAttributionReport. I checked it with 0.6.5 and it is still not producing the correct output.

The SPDX Attribute "extractedText" should be added and should have the same value as the Attribution Report Attribute "licenseReference" I guess!

Here is an example of a nuget Package:

Generated Json with Attribution Report:

    "castle.core.4.4.1.nupkg": [
      {
        "itemNumber": 5,
        "licenses": [
          {
            "license": "Apache 2.0",
            "licenseReference": "https://index.whitesourcesoftware.com/gri/app/reader/resource/content/asString/3020448c-8294-4ed3-9c0f-ebbe3da2076d",
            "licenseText": "License Text Under Appendix"
          }
        ],
        "copyrights": [
          {
            "copyright": "Copyright 2004-2020 Castle Project",
            "copyrightReference": "https://index.whitesourcesoftware.com/gri/app/reader/resource/content/asString/61f46266-b7dc-4f99-b69e-701f6bdcc4ac",
            "author": "Castle Project"
          },
          {
            "copyright": "Copyright 2004-2016 Castle Project",
            "copyrightReference": "https://index.whitesourcesoftware.com/gri/app/reader/resource/content/asString/3f1b15f7-75c7-4f76-9aea-db9031048c57",
            "author": "Castle Project"
          }
        ]
      }
    ],

Generated SPDX Output by ws-sbom-generator 0.6.5:

        {
            "SPDXID": "SPDXRef-PACKAGE-castle.core.4.4.1.nupkg",
            "name": "Castle.Core",
            "downloadLocation": "https://api.nuget.org/packages/castle.core.4.4.1.nupkg",
            "licenseConcluded": "Apache-2.0",
            "licenseInfoFromFiles": [
                "Apache-2.0"
            ],
            "licenseDeclared": "Apache-2.0",
            "copyrightText": "['Copyright 2004-2016 Castle Project', 'Copyright 2004-2020 Castle Project']",
            "versionInfo": "4.4.1",
            "packageFileName": "castle.core.4.4.1.nupkg",
            "supplier": "Organization: Castle Project Contributors (NOASSERTION)",
            "originator": "Organization: Castle Project Contributors (NOASSERTION)",
            "checksums": [
                {
                    "algorithm": "SHA1",
                    "checksumValue": "aa7230a8449a6849af8be6996ce8374b5dab4bf7"
                }
            ],
            "homepage": "https://api.nuget.org/packages/castle.core.4.4.1.nupkg",
            "filesAnalyzed": false
        },

**Comment by DimarrWS** [comment]
Hi @Markus-Wild !  First of all, you can take the new version 0.6.6 with small updates related to getting extractedText data. Second, If I understood your request correctly, I think you are a little bit wrong. 
In SPDX documentation (https://spdx.dev/spdx-specification-21-web-version/) described when Tag "Extracted Text" should be added. 
Item 6.2.2 is "**Intent:  Provide the actual text as found in the package or file for a license that is not on the SPDX License List**."
We are not adding License Text for each library from SPDX License List. 
Just for extracted packages License text is provided, related to official SPDX documentation. 
Related the documentation : the sections for library from SPDX License List contains a different set of fields than a list of Extracted packages. 
If I misunderstood your question, please specify it and I'll be happy to help.

**Comment by Markus-Wild** [comment]
Hi @DimarrWS thanks for your answer. 

So if I understand you right, if I want to extract the "exact/original" Licenstext of a package I do not get this information from the spdx document?! So when I have to include the exact Licenstext of a Package with the delivered software I need a second source to get this information from?

**Comment by DimarrWS** [comment]
Hi @RalfEckstein and @Markus-Wild ! Thank you for your feedback! I understood your requests. 
I will check how better to implement it. 
And, of course, I will check that SPDX output file will be valid after adding extractedTexp into every section. 
I will update you soon.

**Comment by DimarrWS** [comment]
HI @RalfEckstein , @Markus-Wild ! 
We prepared a new release 0.6.7. 
Added two parameters (as described in the Readme file). Now possible to get License text for each library in case we have this text. 
Please, pay attention, that needs to update the package ws-sdk too. The last version of ws-sdk package is 0.11.2

**Comment by Markus-Wild** [comment]
Hi @DimarrWS ,

we just experimented with the new v0.6.8 Version:

ws_sbom_generator -u $env:WS_USERKEY -k $env:WS_APIKEY -s $env:WS_PROJECTTOKEN -a $env:WS_URL -t json -o ./whitesource -e ./whitesource/extra-conf.json --license_text True --out_file "license-information"

what makes me wonder is, that the license text for example of the parse5 package is not listed in the license information file as expected:

[license-information-SPDX-2.2.json.txt](https://github.com/whitesource-ps/ws-sbom-generator/files/9337122/license-information-SPDX-2.2.json.txt)

I expect the content of following link:
https://index.whitesourcesoftware.com/gri/app/reader/resource/content/asString/2a9b1dca-6d7d-4a0c-8e9f-cb38f7433516

Do I understand the meaning of the --license_text parameter wrong or is this still not working correctly?

Thanks,

Markus

**Comment by DimarrWS** [comment]
Hi @Markus-Wild ! Please, take the new version of sbom-generator. We changed the business logic of extra license text preparation.

**Comment by chrisdecker1201** [comment]
@DimarrWS @Markus-Wild For me, it's working now as we (@Markus-Wild is a colleague) expected.

**Comment by Markus-Wild** [comment]
@DimarrWS :Thanks a lot for your effort!
So from my point of view this thread can be closed! 

Kind regards,

Markus

P.S.:
@RalfEckstein: Can you confirm this?

**Comment by NatalyaDalid** [comment]
@Markus-Wild , @RalfEckstein 
thank you for your feedback!

Mend PS Team
